### PR TITLE
🚀[Release v2.13.0 20241220] Merge into Develop

### PR DESCRIPTION
**Pull request by kcw-grunt**
# Overview
This is a quick release to get the recent bugfixes into production to increase stability

## Fixes
- [fix: just close the FragmentRequestAmount if refreshAddress return false](https://github.com/litecoin-foundation/litewallet-android/commit/f3a6d9de2713d2822fc528a20889f9f100086767)
- [fix: fix User unable to set preferred local fiat currency](https://github.com/litecoin-foundation/litewallet-android/commit/2ce1e2fe303fc946549a02147e857eb4af016fec)
- [fix: fix crash android.os.NetworkOnMainThreadException: onPublishTxAuth](https://github.com/litecoin-foundation/litewallet-android/commit/cc1cf623a5e17c7344225257ae2bcd59fb81c63d)

## Improvements
- feat: implement basic AppsFlyer
- Added tests BRConstants MockK+JUnit4

### CODE REVIEW

**Review by josikie — APPROVED** [review]
Cool, thank you! @kcw-grunt

**Review by josikie — COMMENTED** [review]
Is it only contain updated readme?

**Comment by kcw-grunt** [comment]
> Is it only contain updated readme?

Well I wanted to bring in all the updates from Dec 12 / last release. @andhikayuana and I saw a bug and he fixed it 🚀 
I just updated the README to trigger the CircleCI workflow

**Comment by josikie** [comment]
Oh okay, awesome! @kcw-grunt @andhikayuana

**Review by andhikayuana — APPROVED** [review]

**Pull request merged**
