### PR TITLE
🚀[Release v2.13.0] Merge into Main

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Overview
 This release has many bugfixes and includes remote config and tech debt retirements
 
### Bugfixes

- 7 Crashlytics retirements

### Tech debt

- 7 Maintenance and code improvements 

### Features

- Remote configuration capability

### CODE REVIEW

**Review by josikie — APPROVED** [review]
Awesome, thank you! @kcw-grunt

**Review by andhikayuana — APPROVED** [review]
LGTM 🎸 
merci beaucoup!

**Comment by kcw-grunt** [comment]
> LGTM 🎸 merci beaucoup!

Pas de quoi messeur!

**Comment by kcw-grunt** [comment]
> Awesome, thank you! @kcw-grunt

You folks are awesome!

**Comment by kcw-grunt** [comment]
So proud of our progress @andhikayuana  and @josikie 🔥🔥 🔥 🔥 🔥 🔥

**Pull request merged**
