### PR TITLE
Updated target API to level 14 (SDK Version 34)

### PR DESCRIPTION
**Pull request by josikie**
## Overview
Updated target API to level 14 (SDK Version 34).

### CODE REVIEW

**Review by kcw-grunt — COMMENTED** [review]
@josikie .
I know our tests are not good.  But did you run manual tests?  You said the the BRBitcoin was broken?

**Comment by josikie** [comment]
@kcw-grunt 

I clicked built app before make any changes, and it crashed and showed me error on file wallet.c that said it can't find BRLitecoinAmount() function. I tried to change it with BRBitcoinAmount then it didn't crash... I didn't push them here, I just pushed the target api update here. I think we are missing BRLitecoinAmount() function

**Comment by kcw-grunt** [comment]
See the problem you are describing.

Here is the issue I caused.

loafwallet-core has an interface in BRWallet that refers to that is called `BRBitcoinAmount`  and the transition directory in Litewallet-Android refers to that interface.  The problem is I changed the method in Litewallet-Android transition but the loafwallet-core cant find it. 

The fix is to revert and leave it as BRBitcoinAmount because we will retire the loafwallet-core lib soon

**Comment by kcw-grunt** [comment]
Hey @josikie this issue is resolved. Will you rebase and let me know so we can approve?

**Comment by josikie** [comment]
Yes, I will @kcw-grunt

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Pull request merged**
