### PR TITLE
Bugfix - fix IntroActivity image resource crash

### PR DESCRIPTION
**Pull request by vsima**
- fixes crash on IntroActivity - RuntimeException: Canvas: trying to draw too large bitmap
 - firebase url - https://console.firebase.google.com/u/0/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/c54109d4e1f80859c0f339651cce3779

### CODE REVIEW

**Review by josikie — APPROVED** [review]
Great! @vsima

**Review by josikie — APPROVED** [review]

**Review by josikie — APPROVED** [review]

**Comment by kcw-grunt** [comment]
Thanks @vsima !
Will you add the link from Crashlytics so we can refer to the retirement of the bug?

**Comment by kcw-grunt** [comment]
Thanks @vsima !
Will you add the link from Crashlytics so we can refer to the retirement of the bug?

**Comment by vsima** [comment]
Fixes Firebase crash - https://console.firebase.google.com/u/0/project/litewallet-beta/crashlytics/app/android:com.loafwallet/issues/c54109d4e1f80859c0f339651cce3779?time=last-ninety-days&versions=v2.8.1%20(726);v2.8.1%20(725);v2.8.1%20(723)&sessionEventKey=6435D27100010001023282499F97624E_1799354564756179953

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Pull request merged**
