### PR TITLE
Redesign set password and biometrics

### PR DESCRIPTION
**Pull request by josikie**
For redesign UI Wireframe PassCode and Biometrics
What are the features added for compose?
- Passcode (UI & settings preferences)
- Biometrics (UI & settings preferences)
- Dark Mode (UI & settings preferences)
- Language Picker (UI & settings preferences)

### CODE REVIEW

**Review by Getbook1 — CHANGES_REQUESTED** [review]
This is not your wallet

**Comment by kcw-grunt** [comment]
> This is not your wallet 

@Getbook1 Please our team very hard. We don't tolerate trolls.  Please apologize

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Comment by kcw-grunt** [comment]
Sorry for the long delay....finally getting back in @josikie

**Comment by josikie** [comment]
It's ok @kcw-grunt

**Pull request merged**
