### PR TITLE
Feature - Show Litecoin Card as Webview

### LINKED ISSUE #58: 🥳[Feature] Show Litecoin Card as Webview
## Overview
We need to support Litecoin Card at the highest level. Current embedded solutions offer only a limited functionality

### Why?
Using a Webview will reduce our development time and route issues directly to Ternio/Unbanked
 
### Definition of Done
- [ ] Add WebView of : :https://litecoin.dashboard.getblockcard.com/ (e
- [ ] remove modal
- [ ] remove partnerapi
- [ ] Test

## UI Changes

|**Before**|**After**|
|----------|---------|
|Screenshot_20221111-074808||

### PR DESCRIPTION
**Pull request by vsima**
- remove partner api library
 - create card frament webview and add to bottom nav
 - fixes #58

### CODE REVIEW

**Comment by vsima** [comment]
Screenshot

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Thanks but something is wrong when tapping on settings..please see the gif

**Comment by vsima** [comment]
@kcw-grunt Ready for review!

**Review by kcw-grunt — APPROVED** [review]

**Comment by kcw-grunt** [comment]
Thanks @vsima

**Pull request merged**
