### PR TITLE
Added Announcement view to encourage email mailing list

### PR DESCRIPTION
**Pull request by josikie**
Hello!

This pr is for added announcement view to encourage email mailing list on our app.

Test on AVD (I want to test on real device, but Android Studio has problem. It took too long to pair it with wifi, sometimes it success pair the device with android studio, sometimes it failed):

https://github.com/litecoin-foundation/litewallet-android/assets/54074780/acf8dbc9-5233-435c-a630-df62fb2484a1

### CODE REVIEW

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Comment by kcw-grunt** [comment]
Sorry @josikie  I noticed 2 things
1. There  are conflicts. Will you pull develop and resolve the conflicts?
2. Part of the strings.xml file has some "Lorem ipsum" text.  Was that intentional?  I think it needs to be removed.

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Sorry @josikie I noticed 2 things

There are conflicts. Will you pull develop and resolve the conflicts?
Part of the strings.xml file has some "Lorem ipsum" text. Was that intentional? I think it needs to be removed.

**Comment by josikie** [comment]
@kcw-grunt I'll remove it, I think it got added automatically with Android Studio when I created a new activity

**Comment by josikie** [comment]
Hello! @kcw-grunt 
The conflict is resolved

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Pull request merged**
