### PR TITLE
Put announce updates view on create and recreate

### PR DESCRIPTION
**Pull request by josikie**
Hello!

This pr is to direct the user to email subscription form after pressed button create and restore.

### CODE REVIEW

**Comment by kcw-grunt** [comment]
Thanks @josikie going to sleep soon. I will look at it tomorrow.  TYVM!

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Hi @josikie . 
Looks really good. I pulled it and ran it locally.

I made a problem with the cleanup yesterday where some directories went missing.
Will you add them back in? They make PAD work.

You can just add `src/main/assets` under `fast_follow_asset_pack_01`
Push that one commit and I will approve.

|Adding dirs|
|-----------|
|Screenshot 2024-04-06 at 8 35 31 AM|

**Comment by josikie** [comment]
Hello! @kcw-grunt 

Git doesn't want empty to be committed. So I add an empty file too.

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Pull request merged**
